# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Deep Notes
email: thushenhan@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Deep learning and machine learning notes, tutorials, and resources.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://deepnotes.github.io" # the base hostname & protocol for your site
github_username: shenh10

# Social media links
twitter_username: shenh10
linkedin_username: shenh10

# Site metadata
author: shenh10
keywords: deep learning, machine learning, AI, neural networks, tutorials, notes
language: en
timezone: Asia/Shanghai

# Site features
show_excerpts: true
show_related_posts: true
show_post_categories: true
show_post_tags: true

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache

# GitHub Pages specific settings
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false

# Markdown processor settings
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Collections
collections:
  posts:
    output: true
    permalink: /:collection/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "shenh10"
      comments: true
      share: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
# Exclude from processing.
# The following items will not be processed, by default.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .trunk/
  - .DS_Store
  - README.md
  - LICENSE
  - .gitignore
